### ISSUE TITLE
Kafka-Connect SSL

### ISSUE THREAD

**Issue by adamstrawson** [confluentinc/cp-docker-images#189]
This is probably me missing something, but I'm having problems with starting the kafka-connect container when using SSL with Kafka. Specifically when kafka-connect runs `cub kafka-ready`

It looks like `cub kafka-ready` doesn't have any logic to support SSL (similar to how say the changes in Schema-Registry has it)

At the moment, `ensure` only has the following;

```bash
echo "===> Check if Kafka is healthy ..."

cub kafka-ready \
    "${CONNECT_CUB_KAFKA_MIN_BROKERS:-1}" \
    "${CONNECT_CUB_KAFKA_TIMEOUT:-40}" \
    -b "$CONNECT_BOOTSTRAP_SERVERS"
```
so it doesn't know to use SSL. I've set the `env` variable `CONNECT_SECURITY_PROTOCOL=SSL` but the kafka-ready MetadataClientConfig values show `security.protocol = PLAINTEXT`

In Schema-Registry if SSL is used, it reads additional config from `admin.properties` 
```bash
if [[ -n "${SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL-}" ]] && [[ $SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL="SSL" ]]
then
    cub kafka-ready 1 \
        "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
        -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
        --config /etc/"${COMPONENT}"/admin.properties
else
    cub kafka-ready \
        "${SCHEMA_REGISTRY_CUB_KAFKA_MIN_BROKERS:-1}" \
        "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
        -z "$SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL"
fi

```

Is there an issue here, or am I missing something?

When running `ensure` as it currently is, `cub kafka-ready` times out with the below message. Kafka is running as expected, so seems it's just because it's not listening on PLAINTEXT

```
Request METADATA failed against node 10.X.X.X:9092 (id: -1 rack: null).
java.lang.NullPointerException
        at io.confluent.admin.utils.KafkaAdminClient.send(KafkaAdminClient.java:118)
        at io.confluent.admin.utils.KafkaAdminClient.sendAnyNode(KafkaAdminClient.java:102)
        at io.confluent.admin.utils.KafkaAdminClient.findAllBrokers(KafkaAdminClient.java:89)
        at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:127)
        at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:122)
Request METADATA failed on all bootstrap brokers [10.X.X.X:9092 (id: -1 rack: null)].
Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
Expected 1 brokers but found only 0. Brokers found [].
```

**Comment by adamstrawson** [comment]
Related: https://github.com/confluentinc/cp-docker-images/pull/194
