### ISSUE TITLE
Error: Could not initialize class kafka.network.RequestChannel$

### ISSUE THREAD

**Issue by inancgumus** [confluentinc/cp-docker-images#261]
I tried to run Kafka without Docker a few days ago, again, I failed. It's very hard to setup. So, I decided to use Docker, then I failed again. What could be the problem?

----

**I ran these commands:**

```bash
git clone https://github.com/confluentinc/cp-docker-images
cd cp-docker-images/examples/kafka-single-node
docker-compose up
```

**Btw, this is my:**

- Docker version: 17.03.1-ce
- Docker compose version: 1.11.2, build dfed245

I downloaded the new Docker for OS X [here](https://store.docker.com/editions/community/docker-ce-desktop-mac?tab=description).

----

**SIDE NOTE:** _New Docker for OS X uses a different architecture than the previous ones and so, solves many previous problems in OS X with Docker. So, most of the issues talked in Confluent Docker documentation will be easier to address, I believe._

-----

**Error Log:**

```bash
kafka_1      | java.io.IOException: Connection to 1 was disconnected before the response was read
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:114)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:112)
kafka_1      | at scala.Option.foreach(Option.scala:257)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:112)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:108)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$.recursivePoll$1(NetworkClientBlockingOps.scala:136)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$.kafka$utils$NetworkClientBlockingOps$$pollContinuously$extension(NetworkClientBlockingOps.scala:142)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$.blockingSendAndReceive$extension(NetworkClientBlockingOps.scala:108)
kafka_1      | at kafka.controller.RequestSendThread.liftedTree1$1(ControllerChannelManager.scala:196)
kafka_1      | at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:188)
kafka_1      | at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
kafka_1      | [2017-05-08 21:00:37,484] INFO [Controller-1-to-broker-1-send-thread], Controller 1 connected to localhost:29092 (id: 1 rack: null) for sending state change requests (kafka.controller.RequestSendThread)
```

**This is the exception error which keeps repeating itself:**

```bash
kafka_1      | [2017-05-08 21:00:37,486] ERROR Processor got uncaught exception. (kafka.network.Processor)
kafka_1      | java.lang.NoClassDefFoundError: Could not initialize class kafka.network.RequestChannel$
kafka_1      | at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:111)
kafka_1      | at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:513)
kafka_1      | at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:505)
kafka_1      | at scala.collection.Iterator$class.foreach(Iterator.scala:893)
kafka_1      | at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
kafka_1      | at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
kafka_1      | at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
kafka_1      | at kafka.network.Processor.processCompletedReceives(SocketServer.scala:505)
kafka_1      | at kafka.network.Processor.run(SocketServer.scala:433)
kafka_1      | at java.lang.Thread.run(Thread.java:745)
kafka_1      | [2017-05-08 21:01:07,516] WARN [Controller-1-to-broker-1-send-thread], Controller 1 epoch 1 fails to send request (type: UpdateMetadataRequest=, controllerId=1, controllerEpoch=1, partitionStates={}, liveBrokers=(id=1, endPoints=(host=localhost, port=29092, listenerName=ListenerName(PLAINTEXT), securityProtocol=PLAINTEXT), rack=null)) to broker localhost:29092 (id: 1 rack: null). Reconnecting to broker. (kafka.controller.RequestSendThread)
kafka_1      | java.io.IOException: Connection to 1 was disconnected before the response was read
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:114)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:112)
kafka_1      | at scala.Option.foreach(Option.scala:257)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:112)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:108)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$.recursivePoll$1(NetworkClientBlockingOps.scala:136)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$.kafka$utils$NetworkClientBlockingOps$$pollContinuously$extension(NetworkClientBlockingOps.scala:142)
kafka_1      | at kafka.utils.NetworkClientBlockingOps$.blockingSendAndReceive$extension(NetworkClientBlockingOps.scala:108)
kafka_1      | at kafka.controller.RequestSendThread.liftedTree1$1(ControllerChannelManager.scala:196)
kafka_1      | at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:188)
kafka_1      | at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
kafka_1      | [2017-05-08 21:01:07,618] INFO [Controller-1-to-broker-1-send-thread], Controller 1 connected to localhost:29092 (id: 1 rack: null) for sending state change requests (kafka.controller.RequestSendThread)
kafka_1      | [2017-05-08 21:01:07,619] ERROR Processor got uncaught exception. (kafka.network.Processor)
kafka_1      | java.lang.NoClassDefFoundError: Could not initialize class kafka.network.RequestChannel$
kafka_1      | at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:111)
kafka_1      | at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:513)
kafka_1      | at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:505)
kafka_1      | at scala.collection.Iterator$class.foreach(Iterator.scala:893)
kafka_1      | at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
kafka_1      | at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
kafka_1      | at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
kafka_1      | at kafka.network.Processor.processCompletedReceives(SocketServer.scala:505)
kafka_1      | at kafka.network.Processor.run(SocketServer.scala:433)
kafka_1      | at java.lang.Thread.run(Thread.java:745)
```

**Comment by inancgumus** [comment]
This [#PR](https://github.com/confluentinc/cp-docker-images/pull/258) solves this.

**Comment by tianwaideren** [comment]
How to solve this?

**Comment by wangxfbelieve** [comment]
Your need to set hosts in the /etc/hosts, like this:
`xx.xx.xx.xx kafka`

**Comment by MihaiBogdanEugen** [comment]
I'm also having this issue. I'm using 
```shell
Docker version 17.06.2-ce, build cec0b72
docker-compose version 1.14.0, build c7bdf9e
docker-machine version 0.12.2, build 9371605
```

@wangxfbelieve can you be more specific? What have you wrote in the hosts file?

**Comment by gerardnico** [comment]
#258 solves the problem only if the machine host name is `moby`. It was not the case for me on Windows.

I have read the variable `DOCKER_MACHINE_NAME`. As it was `default`, I have added an extra default host in the `docker-compose.yml` file.

```
extra_hosts:
      - "moby:127.0.0.1"
      - "default:127.0.0.1"
```

Thanks
Nico
