### ISSUE TITLE
Kafka REST SASL_SSL support

### ISSUE THREAD

**Issue by yacut** [confluentinc/cp-docker-images#319]
I have an issue with Kafka-rest SASL_SSL Kafka and zookeeper PLAINTEXT setup.
I can start the server without problems and also get the topic list `curl "http://localhost:8082/topics"`.
But if I try to get a message `curl "http://localhost:8082/topics/test/partitions/0/messages"`, the server throws:

```
[2017-08-23 15:13:36,264] INFO Server started, listening for requests... (io.confluent.kafkarest.KafkaRestMain:59)
[2017-08-23 15:13:50,320] DEBUG Creating SimpleConsumer with id rest-simpleconsumer-1 (host:localhost, port:9092) (io.confluent.kafkarest.SimpleConsumerManager:67)
[2017-08-23 15:13:50,361] DEBUG Simple consumer rest-simpleconsumer-1: fetch 1; 1 messages remaining (io.confluent.kafkarest.SimpleConsumerManager:155)
[2017-08-23 15:13:50,387] DEBUG Disconnecting from localhost:9092 (kafka.consumer.SimpleConsumer:54)
[2017-08-23 15:13:50,391] INFO Reconnect due to error: (kafka.consumer.SimpleConsumer:78)
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:112)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:88)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:86)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:135)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:135)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:135)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:134)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:134)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:134)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:133)
	at kafka.javaapi.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:49)
	at kafka.javaapi.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:59)
	at io.confluent.kafkarest.SimpleFetcher.fetch(SimpleFetcher.java:38)
	at io.confluent.kafkarest.SimpleConsumerManager.fetchRecords(SimpleConsumerManager.java:339)
	at io.confluent.kafkarest.SimpleConsumerManager.consume(SimpleConsumerManager.java:158)
	at io.confluent.kafkarest.resources.PartitionsResource.consume(PartitionsResource.java:210)
	at io.confluent.kafkarest.resources.PartitionsResource.consumeBinary(PartitionsResource.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:408)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:583)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:524)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:461)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
[2017-08-23 15:13:50,394] DEBUG Disconnecting from localhost:9092 (kafka.consumer.SimpleConsumer:54)
[2017-08-23 15:13:50,394] DEBUG Disconnecting from localhost:9092 (kafka.consumer.SimpleConsumer:54)
[2017-08-23 15:13:50,395] DEBUG Disconnecting from localhost:9092 (kafka.consumer.SimpleConsumer:54)
[2017-08-23 15:13:50,403] DEBUG Releasing into the pool SimpleConsumer with id rest-simpleconsumer-1 (io.confluent.kafkarest.SimpleConsumerPool:99)
```

Rest response:
`{"error_code":50002,"message":"Kafka error: null ..."}`

I don't understand, why the SimpleConsumer tries connect to `localhost:9092`.
In the **kafka-rest.properties** bootstrap servers set to `SASL_SSL://kafka:9193`:
```
zookeeper.connect=zookeeper:2181
bootstrap.servers=SASL_SSL://kafka:9193
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="...";
security.protocol=SASL_SSL
ssl.truststore.password=...
ssl.keystore.password=...
ssl.key.password=...
ssl.truststore.location=/truststore.jks
ssl.keystore.location=/keystore.jks
ssl.client.auth=true
```
Should I set another bootstrap servers property? 
I found nothing about SimpleConsumer properties in [the configuration description](http://docs.confluent.io/current/kafka-rest/docs/config.html).
Anybody.... idea....?

**Comment by yacut** [comment]
I found the solution: change advertised host and listeners from `localhost` to docker hostname e.g. `kafka`.
```
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka:9193"
```
