### ISSUE TITLE
ERROR Processor got uncaught exception. (kafka.network.Processor)

### ISSUE THREAD

**Issue by andreeasalinca** [confluentinc/cp-docker-images#330]
I'm trying to run the [kafka-single-node docker-compose example](https://github.com/confluentinc/cp-docker-images/blob/3.3.x/examples/kafka-single-node/docker-compose.yml). 

I'm running the following, on a MacOSX setup:
```shell
Docker version 17.06.2-ce, build cec0b72
docker-compose version 1.14.0, build c7bdf9e
docker-machine version 0.12.2, build 9371605
```

I've created a docker machine just as [instructed](http://docs.confluent.io/current/cp-docker-images/docs/quickstart.html#running-confluent-platform-on-docker).

I am able to star the containers using:
```shell
docker-compose up -d
Creating kafkasinglenode_zookeeper_1 ... 
Creating kafkasinglenode_zookeeper_1 ... done
Creating kafkasinglenode_kafka_1 ... 
Creating kafkasinglenode_kafka_1 ... done
```
But when I check the logs:
```shell
docker logs kafkasinglenode_kafka_1
```
I get the following error
```shell
[2017-09-11 19:27:03,688] INFO starting (kafka.server.KafkaServer)
[2017-09-11 19:27:03,689] INFO Connecting to zookeeper on localhost:32181 (kafka.server.KafkaServer)
[2017-09-11 19:27:03,703] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-09-11 19:27:04,669] INFO Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,669] INFO Client environment:host.name=<NA> (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,669] INFO Client environment:java.version=1.8.0_102 (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,669] INFO Client environment:java.vendor=Azul Systems, Inc. (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,669] INFO Client environment:java.home=/usr/lib/jvm/zulu-8-amd64/jre (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,669] INFO Client environment:java.class.path=:/usr/bin/../share/java/kafka/scala-parser-combinators_2.11-1.0.4.jar:/usr/bin/../share/java/kafka/jackson-databind-2.8.5.jar:/usr/bin/../share/java/kafka/jersey-guava-2.24.jar:/usr/bin/../share/java/kafka/commons-beanutils-1.8.3.jar:/usr/bin/../share/java/kafka/jetty-server-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/jackson-core-asl-1.9.13.jar:/usr/bin/../share/java/kafka/kafka_2.11-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/javax.inject-1.jar:/usr/bin/../share/java/kafka/jersey-client-2.24.jar:/usr/bin/../share/java/kafka/hk2-api-2.5.0-b05.jar:/usr/bin/../share/java/kafka/slf4j-api-1.7.25.jar:/usr/bin/../share/java/kafka/httpcore-4.4.4.jar:/usr/bin/../share/java/kafka/jackson-jaxrs-json-provider-2.8.5.jar:/usr/bin/../share/java/kafka/kafka_2.11-0.11.0.0-cp1-scaladoc.jar:/usr/bin/../share/java/kafka/jackson-jaxrs-base-2.8.5.jar:/usr/bin/../share/java/kafka/hk2-utils-2.5.0-b05.jar:/usr/bin/../share/java/kafka/log4j-1.2.17.jar:/usr/bin/../share/java/kafka/jackson-annotations-2.8.5.jar:/usr/bin/../share/java/kafka/jackson-mapper-asl-1.9.13.jar:/usr/bin/../share/java/kafka/javax.annotation-api-1.2.jar:/usr/bin/../share/java/kafka/jopt-simple-5.0.3.jar:/usr/bin/../share/java/kafka/connect-transforms-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/jersey-common-2.24.jar:/usr/bin/../share/java/kafka/jetty-http-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/connect-api-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/support-metrics-common-3.3.0.jar:/usr/bin/../share/java/kafka/jackson-core-2.8.5.jar:/usr/bin/../share/java/kafka/lz4-1.3.0.jar:/usr/bin/../share/java/kafka/avro-1.8.2.jar:/usr/bin/../share/java/kafka/jetty-continuation-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/aopalliance-repackaged-2.5.0-b05.jar:/usr/bin/../share/java/kafka/zookeeper-3.4.10.jar:/usr/bin/../share/java/kafka/metrics-core-2.2.0.jar:/usr/bin/../share/java/kafka/snappy-java-1.1.2.6.jar:/usr/bin/../share/java/kafka/kafka-clients-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/kafka_2.11-0.11.0.0-cp1-test.jar:/usr/bin/../share/java/kafka/commons-digester-1.8.1.jar:/usr/bin/../share/java/kafka/httpclient-4.5.2.jar:/usr/bin/../share/java/kafka/jersey-container-servlet-core-2.24.jar:/usr/bin/../share/java/kafka/kafka_2.11-0.11.0.0-cp1-javadoc.jar:/usr/bin/../share/java/kafka/javassist-3.21.0-GA.jar:/usr/bin/../share/java/kafka/xz-1.5.jar:/usr/bin/../share/java/kafka/reflections-0.9.11.jar:/usr/bin/../share/java/kafka/connect-file-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/kafka-tools-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/commons-validator-1.4.1.jar:/usr/bin/../share/java/kafka/commons-lang3-3.1.jar:/usr/bin/../share/java/kafka/commons-codec-1.9.jar:/usr/bin/../share/java/kafka/kafka.jar:/usr/bin/../share/java/kafka/plexus-utils-3.0.24.jar:/usr/bin/../share/java/kafka/zkclient-0.10.jar:/usr/bin/../share/java/kafka/scala-library-2.11.11.jar:/usr/bin/../share/java/kafka/commons-lang3-3.5.jar:/usr/bin/../share/java/kafka/paranamer-2.7.jar:/usr/bin/../share/java/kafka/jackson-module-jaxb-annotations-2.8.5.jar:/usr/bin/../share/java/kafka/jetty-servlets-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/jersey-container-servlet-2.24.jar:/usr/bin/../share/java/kafka/connect-json-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/kafka-streams-examples-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/commons-collections-3.2.1.jar:/usr/bin/../share/java/kafka/jetty-security-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/rocksdbjni-5.0.1.jar:/usr/bin/../share/java/kafka/jetty-io-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/validation-api-1.1.0.Final.jar:/usr/bin/../share/java/kafka/argparse4j-0.7.0.jar:/usr/bin/../share/java/kafka/hk2-locator-2.5.0-b05.jar:/usr/bin/../share/java/kafka/kafka_2.11-0.11.0.0-cp1-sources.jar:/usr/bin/../share/java/kafka/connect-runtime-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/kafka_2.11-0.11.0.0-cp1-test-sources.jar:/usr/bin/../share/java/kafka/slf4j-log4j12-1.7.25.jar:/usr/bin/../share/java/kafka/kafka-log4j-appender-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/javax.servlet-api-3.1.0.jar:/usr/bin/../share/java/kafka/javax.inject-2.5.0-b05.jar:/usr/bin/../share/java/kafka/osgi-resource-locator-1.0.1.jar:/usr/bin/../share/java/kafka/commons-compress-1.8.1.jar:/usr/bin/../share/java/kafka/support-metrics-client-3.3.0.jar:/usr/bin/../share/java/kafka/javax.ws.rs-api-2.0.1.jar:/usr/bin/../share/java/kafka/jetty-servlet-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/jersey-server-2.24.jar:/usr/bin/../share/java/kafka/guava-20.0.jar:/usr/bin/../share/java/kafka/maven-artifact-3.5.0.jar:/usr/bin/../share/java/kafka/httpmime-4.5.2.jar:/usr/bin/../share/java/kafka/jetty-util-9.2.15.v20160210.jar:/usr/bin/../share/java/kafka/kafka-streams-0.11.0.0-cp1.jar:/usr/bin/../share/java/kafka/commons-logging-1.2.jar:/usr/bin/../share/java/kafka/jersey-media-jaxb-2.24.jar:/usr/bin/../share/java/confluent-support-metrics/*:/usr/share/java/confluent-support-metrics/* (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:os.version=4.4.86-boot2docker (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,670] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,674] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,674] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,675] INFO Initiating client connection, connectString=localhost:32181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@3427b02d (org.apache.zookeeper.ZooKeeper)
[2017-09-11 19:27:04,686] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:32181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-09-11 19:27:04,687] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2017-09-11 19:27:04,759] INFO Socket connection established to localhost/0:0:0:0:0:0:0:1:32181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-09-11 19:27:04,764] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:32181, sessionid = 0x15e7268a8420001, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2017-09-11 19:27:04,765] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2017-09-11 19:27:04,864] INFO Cluster ID = E8tjf1GdRG6kaBci1RCqSA (kafka.server.KafkaServer)
[2017-09-11 19:27:04,871] WARN No meta.properties file under dir /var/lib/kafka/data/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2017-09-11 19:27:04,897] INFO [ThrottledRequestReaper-Fetch]: Starting (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2017-09-11 19:27:04,899] INFO [ThrottledRequestReaper-Produce]: Starting (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2017-09-11 19:27:04,904] INFO [ThrottledRequestReaper-Request]: Starting (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2017-09-11 19:27:04,933] INFO Loading logs. (kafka.log.LogManager)
[2017-09-11 19:27:04,938] INFO Logs loading complete in 5 ms. (kafka.log.LogManager)
[2017-09-11 19:27:04,964] INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager)
[2017-09-11 19:27:04,966] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2017-09-11 19:27:04,969] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-09-11 19:27:04,973] INFO [kafka-log-cleaner-thread-0]: Starting (kafka.log.LogCleaner)
[2017-09-11 19:27:05,024] INFO Awaiting socket connections on 0.0.0.0:29092. (kafka.network.Acceptor)
[2017-09-11 19:27:05,034] INFO [Socket Server on Broker 1], Started 1 acceptor threads (kafka.network.SocketServer)
[2017-09-11 19:27:05,047] INFO [ExpirationReaper-1-Produce]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2017-09-11 19:27:05,049] INFO [ExpirationReaper-1-Fetch]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2017-09-11 19:27:05,052] INFO [ExpirationReaper-1-DeleteRecords]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2017-09-11 19:27:05,095] INFO [controller-event-thread]: Starting (kafka.controller.ControllerEventManager$ControllerEventThread)
[2017-09-11 19:27:05,099] INFO [ExpirationReaper-1-topic]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2017-09-11 19:27:05,103] INFO Creating /controller (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2017-09-11 19:27:05,106] INFO [ExpirationReaper-1-Heartbeat]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2017-09-11 19:27:05,122] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
[2017-09-11 19:27:05,122] INFO [Controller 1]: 1 successfully elected as the controller (kafka.controller.KafkaController)
[2017-09-11 19:27:05,122] INFO [ExpirationReaper-1-Rebalance]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2017-09-11 19:27:05,129] INFO [Controller 1]: Broker 1 starting become controller state transition (kafka.controller.KafkaController)
[2017-09-11 19:27:05,137] INFO [Controller 1]: Controller 1 incremented epoch to 1 (kafka.controller.KafkaController)
[2017-09-11 19:27:05,140] DEBUG [Controller 1]: Registering IsrChangeNotificationListener (kafka.controller.KafkaController)
[2017-09-11 19:27:05,162] INFO [GroupCoordinator 1]: Starting up. (kafka.coordinator.group.GroupCoordinator)
[2017-09-11 19:27:05,172] INFO [GroupCoordinator 1]: Startup complete. (kafka.coordinator.group.GroupCoordinator)
[2017-09-11 19:27:05,174] INFO [Group Metadata Manager on Broker 1]: Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2017-09-11 19:27:05,186] INFO [Controller 1]: Partitions being reassigned: Map() (kafka.controller.KafkaController)
[2017-09-11 19:27:05,194] INFO [Controller 1]: Partitions already reassigned: Set() (kafka.controller.KafkaController)
[2017-09-11 19:27:05,196] INFO [Controller 1]: Resuming reassignment of partitions: Map() (kafka.controller.KafkaController)
[2017-09-11 19:27:05,192] INFO [ProducerId Manager 1]: Acquired new producerId block (brokerId:1,blockStartProducerId:0,blockEndProducerId:999) by writing to Zk with path version 1 (kafka.coordinator.transaction.ProducerIdManager)
[2017-09-11 19:27:05,204] INFO [Controller 1]: Currently active brokers in the cluster: Set() (kafka.controller.KafkaController)
[2017-09-11 19:27:05,204] INFO [Controller 1]: Currently shutting brokers in the cluster: Set() (kafka.controller.KafkaController)
[2017-09-11 19:27:05,207] INFO [Controller 1]: Current list of topics in the cluster: Set() (kafka.controller.KafkaController)
[2017-09-11 19:27:05,211] INFO [Controller 1]: List of topics to be deleted:  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,213] INFO [Controller 1]: List of topics ineligible for deletion:  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,248] INFO [Transaction Coordinator 1]: Starting up. (kafka.coordinator.transaction.TransactionCoordinator)
[2017-09-11 19:27:05,258] INFO [Replica state machine on controller 1]: Started replica state machine with initial state -> Map() (kafka.controller.ReplicaStateMachine)
[2017-09-11 19:27:05,260] INFO [Partition state machine on Controller 1]: Started partition state machine with initial state -> Map() (kafka.controller.PartitionStateMachine)
[2017-09-11 19:27:05,266] INFO [Controller 1]: Broker 1 is ready to serve as the new controller with epoch 1 (kafka.controller.KafkaController)
[2017-09-11 19:27:05,267] INFO [Transaction Coordinator 1]: Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2017-09-11 19:27:05,275] INFO [Transaction Marker Channel Manager 1]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2017-09-11 19:27:05,278] INFO [Controller 1]: Partitions undergoing preferred replica election:  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,284] INFO [Controller 1]: Partitions that completed preferred replica election:  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,284] INFO [Controller 1]: Skipping preferred replica election for partitions due to topic deletion:  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,285] INFO [Controller 1]: Resuming preferred replica election for partitions:  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,285] INFO [Controller 1]: Starting preferred replica leader election for partitions  (kafka.controller.KafkaController)
[2017-09-11 19:27:05,286] INFO [Partition state machine on Controller 1]: Invoking state change to OnlinePartition for partitions  (kafka.controller.PartitionStateMachine)
[2017-09-11 19:27:05,310] INFO [Controller 1]: starting the controller scheduler (kafka.controller.KafkaController)
[2017-09-11 19:27:05,367] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
[2017-09-11 19:27:05,400] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2017-09-11 19:27:05,431] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
[2017-09-11 19:27:05,432] INFO Registered broker 1 at path /brokers/ids/1 with addresses: EndPoint(localhost,29092,ListenerName(PLAINTEXT),PLAINTEXT) (kafka.utils.ZkUtils)
[2017-09-11 19:27:05,450] WARN No meta.properties file under dir /var/lib/kafka/data/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2017-09-11 19:27:05,485] INFO [Controller 1]: Newly added brokers: 1, deleted brokers: , all live brokers: 1 (kafka.controller.KafkaController)
[2017-09-11 19:27:05,488] INFO Kafka version : 0.11.0.0-cp1 (org.apache.kafka.common.utils.AppInfoParser)
[2017-09-11 19:27:05,496] INFO Kafka commitId : 6a8cf706ddc9ab6a (org.apache.kafka.common.utils.AppInfoParser)
[2017-09-11 19:27:05,496] INFO [Kafka Server 1], started (kafka.server.KafkaServer)
[2017-09-11 19:27:05,499] DEBUG [Channel manager on controller 1]: Controller 1 trying to connect to broker 1 (kafka.controller.ControllerChannelManager)
[2017-09-11 19:27:05,517] INFO [Controller 1]: New broker startup callback for 1 (kafka.controller.KafkaController)
[2017-09-11 19:27:05,521] INFO [Controller-1-to-broker-1-send-thread]: Starting (kafka.controller.RequestSendThread)
[2017-09-11 19:27:05,530] INFO [Controller-1-to-broker-1-send-thread]: Controller 1 connected to localhost:29092 (id: 1 rack: null) for sending state change requests (kafka.controller.RequestSendThread)
[2017-09-11 19:27:05,634] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ExceptionInInitializerError
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:124)
	at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:518)
	at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:511)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:511)
	at kafka.network.Processor.run(SocketServer.scala:436)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: confluent: confluent: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at kafka.network.RequestChannel$.<init>(RequestChannel.scala:43)
	at kafka.network.RequestChannel$.<clinit>(RequestChannel.scala)
	... 10 more
Caused by: java.net.UnknownHostException: confluent: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 12 more
```
It might be related to the Docker on MacOSX setup, but from browsing similar issues I was under the impression that using moby extra host should solve this issue.
Any hints?

**Comment by MihaiBogdanEugen** [comment]
I have exactly the same issue...

**Comment by andreeasalinca** [comment]
Removing the moby extra hosts from docker-compose apparently solves the issue.
