### ISSUE TITLE
java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by vlad1777d** [confluentinc/cp-docker-images#395]
System: Mac 10.13.1
Docker: 17.09.0-ce-mac35
Docker-compose .yml file: [docker-compose.yml.txt](https://github.com/confluentinc/cp-docker-images/files/1591550/docker-compose.yml.txt)

```
root@9d6c33e48727:/# /usr/bin/kafka-avro-console-producer --broker-list  kafka:9092,registry:8081 --topic test-topic --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
{"f1": "value1"}
[2017-12-28 15:53:34,265] ERROR Failed to send HTTP request to endpoint: http://localhost:8081/subjects/test-topic-value/versions (io.confluent.kafka.schemaregistry.client.rest.RestService:165)
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:161)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:218)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:307)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:299)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:294)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:61)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:100)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:79)
	at io.confluent.kafka.formatter.AvroMessageReader.readMessage(AvroMessageReader.java:166)
	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:59)
	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:161)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:218)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:307)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:299)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:294)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:61)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:100)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:79)
	at io.confluent.kafka.formatter.AvroMessageReader.readMessage(AvroMessageReader.java:166)
	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:59)
	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
```

The problem is that Schema Registry's service address seems to be hardcoded or wrongly detected. It must be not localhost:8081, but registry:8081.
There is no ability to specify this address to avro console producer.

**Comment by asdf2014** [comment]
@vlad1777d Check your schema register process is healthy?

**Comment by cricket007** [comment]
This seems to be a typo... `registry:8081` should not be in the `broker-list` option. 

The hard-coded `http://localhost:8081` comes from `kafka-avro-console-producer`, and is because you *forgot* to include a `--property schema.registry.url` parameter
