### ISSUE TITLE
Unknown configuration 'errors.deadletterqueue.topic.name'

### ISSUE THREAD

**Issue by kloba** [confluentinc/cp-docker-images#523]
Hello,

Please help to solve a problem with configuration PubSub Sink Kafka Connect.
My configuration:
`curl -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{ "name": "pubsub_test", "config": { "connector.class": "com.google.pubsub.kafka.sink.CloudPubSubSinkConnector", "tasks.max": "1", "topics": "kafka_test_topic", "cps.topic": "cps_test_topic", "cps.project": "cps_test_project" } }' http://localhost:8083/connectors`

Than in status, I have a following message:
`{"name":"pubsub_test","connector":{"state":"RUNNING","worker_id":"connect:8083"},"tasks":[{"state":"FAILED","trace":"org.apache.kafka.common.config.ConfigException: Unknown configuration 'errors.deadletterqueue.topic.name'\n\tat org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:91)\n\tat org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig.get(ConnectorConfig.java:117)\n\tat org.apache.kafka.connect.runtime.ConnectorConfig.get(ConnectorConfig.java:162)\n\tat org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:126)\n\tat org.apache.kafka.connect.runtime.Worker.sinkTaskReporters(Worker.java:531)\n\tat org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:508)\n\tat org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:451)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:873)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:111)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:888)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:884)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","id":0,"worker_id":"connect:8083"}],"type":"sink"}`

**Comment by asifakb** [comment]
[




connect            |  (org.apache.kafka.connect.runtime.errors.LogReporter$LogReporterConfig)
connect            | [2018-08-02 18:18:43,783] ERROR Failed to start task custdb-s3-connector-0 (org.apache.kafka.connect.runtime.Worker)
connect            | org.apache.kafka.common.config.ConfigException: Unknown configuration 'errors.deadletterqueue.topic.name'
connect            |    at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:91)
connect            |    at org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig.get(ConnectorConfig.java:117)
connect            |    at org.apache.kafka.connect.runtime.ConnectorConfig.get(ConnectorConfig.java:162)
connect            |    at org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:126)
connect            |    at org.apache.kafka.connect.runtime.Worker.sinkTaskReporters(Worker.java:531)
connect            |    at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:508)
connect            |    at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:451)
connect            |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:873)
connect            |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:111)
connect            |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:888)
connect            |    at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:884)
connect            |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect            |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect            |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect            |    at java.lang.Thread.run(Thread.java:748)


](I am also getting similar error. Unknown configuration error.)
