### ISSUE TITLE
Confluent Enterprise QuickStart not working on Docker for Windows

### ISSUE THREAD

**Issue by AndyNorris** [confluentinc/cp-docker-images#636]
I am trying to run the docker quickstart on Docker for windows by following the instructions here 
https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html#ce-docker-quickstart

This is failing on the build step docker-compose up -d --build with the following error:

PS C:\Users\andyw\cp-docker-images\examples\cp-all-in-one> docker-compose up -d --build
Building connect
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1080, in up
  File "compose\cli\main.py", line 1076, in up
  File "compose\project.py", line 475, in up
  File "compose\service.py", line 340, in ensure_image_exists
  File "compose\service.py", line 1080, in build
  File "site-packages\docker\api\build.py", line 142, in build
TypeError: You must specify a directory to build in path
[13908] Failed to execute script docker-compose

**Comment by AndyNorris** [comment]
Managed to fix this my self by downloading the docker file manually and putting into a new folder under cp-all-in-one and then changing the docker compose yml to use a file reference rather than an http reference

**Comment by DaveSlinn** [comment]
Docker for Windows updated to version 2.0 earlier this week and I retested this and it is working now.
