### ISSUE TITLE
Unknown datum class: class java.lang.Short with 5.1.0

### ISSUE THREAD

**Issue by ankit45621** [confluentinc/cp-docker-images#755]
Hello everyone,

I am getting following issue with image version 5.1.0:

org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:269)
at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:293)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:228)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.avro.AvroRuntimeException: Unknown datum class: class java.lang.Short
at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
at org.apache.avro.Schema$Field.(Schema.java:423)
at org.apache.avro.Schema$Field.(Schema.java:415)
at io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:964)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:847)
at io.confluent.connect.avro.AvroData.fromConnectSchemaWithCycle(AvroData.java:942)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:834)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:689)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:683)
at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:328)
at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:76)
at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:269)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
... 11 more

**Comment by cricket007** [comment]
Hello. 

This appears to be an issue with your Avro schema or the Avro deserializer, not the Docker images.

Therefore, this issue would be better asked elsewhere, such as Stackoverflow or Confluent community Slack.
