### ISSUE TITLE
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING

### ISSUE THREAD

**Issue by lcalviny** [confluentinc/cp-docker-images#813]
winpty docker-compose exec kafka  \
> kafka-topics --create --topic foo --partitions 1 --replication-factor 1 --if-not-exists --zookeeper localhost:32181
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:258)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:254)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:112)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1826)
        at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:280)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:53)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)

**Comment by brmeloleite01** [comment]
+1

**Comment by aymen-ba** [comment]
+1

**Comment by bmoe24x** [comment]
Same thing here

**Comment by neilcook** [comment]
Use --zookeeper zookeeper:2181 instead and it will work

**Comment by prabhupatel** [comment]
using port 2181 but not sure why it is throwing the same exception

**Comment by abenmariem** [comment]
The solution is to make these modifications to the Kafka server configuration file:
- zookeeper.connection.timeout.ms=60000
- #broker.id=0
I have created a tutorial which teaches [how to install kafka on windows 10](https://javasneo.blogspot.com/2021/01/install-apache-kafka-on-windows-10.html) with the latest version of kafka.

**Comment by neemiasjnr** [comment]
I had this problem on Kafka 2.7 and it worked when using `--bootstrap-server localhost:9092` instead of zookeeper (zk connection is deprecated on newest versions of Kafka).

**Comment by muzammilzuberi** [comment]
I change maxClientCnxns=0 to maxClientCnxns=1 and it worked
