### ISSUE TITLE
Unexpected error from /xx.xx.xx.xxx; closing connection

### ISSUE THREAD

**Issue by yinhejianke** [confluentinc/cp-docker-images#869]
[2020-08-11 01:49:34,315] WARN [SocketServer brokerId=0] Unexpected error from /172.20.0.220; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 104857600)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
        at kafka.network.Processor.poll(SocketServer.scala:893)
        at kafka.network.Processor.run(SocketServer.scala:792)
        at java.lang.Thread.run(Thread.java:748)

**Comment by yinhejianke** [comment]
change server.properties . not used
