### ISSUE TITLE
Confluent community confluentinc/cp-kafka:7.0.1 giving ClassNotFoundException:io.confluent.metrics.reporter.ConfluentMetricsReporter

### ISSUE THREAD

**Issue by glitch-k8s** [confluentinc/cp-docker-images#916]
**Objective**: I am trying to install Confluent kafka community version using Helm command (Helm version 3).
                       Enterprise image is working successfully.

**Command** :  helm install my-kafka confluentinc/cp-helm-charts --set cp-schema-registry.enabled=false,cp-kafka-rest.enabled=false,cp-kafka-connect.enabled=false,cp-ksql-server.enabled=false,cp-control-center.enabled=false --set cp-zookeeper.imageTag=7.0.1,cp-zookeeper.persistence.enabled=false --set cp-kafka.persistence.enabled=false,cp-kafka.prometheus.jmx.enabled=false --set **cp-kafka.image=confluentinc/cp-kafka,cp-kafka.imageTag=7.0.1**,cp-kafka.nodeport.enabled=true,**cp-kafka.configurationOverrides.CONFLUENT_SUPPORT_METRICS_ENABLE=false**

**Output**:
- zookeeper is getting successfully installed
- kafka pods are giving exception
[2022-02-14 15:47:14,123] INFO [GroupCoordinator 0]: Startup complete. (kafka.coordinator.group.GroupCoordinator)
[2022-02-14 15:47:14,154] INFO [TransactionCoordinator id=0] Starting up. (kafka.coordinator.transaction.TransactionCoordinator)
[2022-02-14 15:47:14,169] INFO [TransactionCoordinator id=0] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2022-02-14 15:47:14,172] INFO [Transaction Marker Channel Manager 0]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2022-02-14 15:47:14,212] INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-02-14 15:47:14,224] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
**org.apache.kafka.common.KafkaException: Class io.confluent.metrics.reporter.ConfluentMetricsReporter cannot be found**
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:396)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:478)
        at kafka.server.DynamicMetricsReporters.createReporters(DynamicBrokerConfig.scala:800)
        at kafka.server.DynamicMetricsReporters.<init>(DynamicBrokerConfig.scala:749)
        at kafka.server.DynamicBrokerConfig.addReconfigurables(DynamicBrokerConfig.scala:248)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:408)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
**Caused by: java.lang.ClassNotFoundException: io.confluent.metrics.reporter.ConfluentMetricsReporter**
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:417)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:406)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:394)
        ... 7 more
[2022-02-14 15:47:14,228] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2022-02-14 15:47:14,230] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Stopping socket server request processors (kafka.network.SocketServer)
[2022-02-14 15:47:14,234] INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Stopped socket server request processors (kafka.network.SocketServer)
[2022-02-14 15:47:14,235] INFO [data-plane Kafka Request Handler on Broker 0], shutting down (kafka.server.KafkaRequestHandlerPool)
[2022-02-14 15:47:14,240] INFO [data-plane Kafka Request Handler on Broker 0], shut down completely (kafka.server.KafkaRequestHandlerPool)
[2022-02-14 15:47:14,246] INFO [ExpirationReaper-0-AlterAcls]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2022-02-14 15:47:

**Comment by andrewegel** [comment]
Please open an issue here: https://github.com/confluentinc/kafka-images/issues
